### ISSUE TITLE
Default version chosen by PkgDev.tag is sometimes unacceptable to METADATA.jl

### ISSUE THREAD

**Issue by simonster** [JuliaLang/PkgDev.jl#88] opened 2016-11-08 18:13 UTC
If the required Julia version has changed since the last minor release, `PkgDev.tag("PkgName")` should tag a new minor version rather than a patch.

**Comment by tkelman** [comment] 2016-11-09 16:14
duplicate of https://github.com/JuliaLang/PkgDev.jl/issues/72

**Comment by simonster** [comment] 2016-11-09 16:16
No, it's not. #72 is about PkgDev telling you when you screwed up. This is about making PkgDev not screw up.

**Comment by tkelman** [comment] 2016-11-09 16:19
We should probably just deprecate single-argument tag, and always require you to specify whether you want patch, minor, or major. If you ask for patch when metadata would reject it, I could see making that give you a warning, or an "are you sure" confirmation prompt when in interactive mode.

**Closed** 2019-11-12 23:50 UTC
Labels: bug
