### ISSUE TITLE
`Pkg.publish()` unable to validate METADATA

### ISSUE THREAD

**Issue by iamed2** [JuliaLang/PkgDev.jl#56] opened 2016-07-28 17:23 UTC
On 0.5.0-rc0 and PkgDev master.

I kept getting this:
```julia
julia> PkgDev.publish()
INFO: Validating METADATA
ERROR: packages with unsatisfiable requirements found:
    BayesNets v0.0.2 – no valid versions exist for package DataFrames
    BayesNets v0.0.3 – no valid versions exist for package DataFrames
    BayesNets v0.0.4 – no valid versions exist for package DataFrames
    BayesNets v0.0.5 – no valid versions exist for package DataFrames
    BayesNets v0.0.6 – no valid versions exist for package DataFrames
    BayesNets v0.0.7 – no valid versions exist for package DataFrames
    BayesNets v0.0.8 – no valid versions exist for package DataFrames
    BayesNets v0.0.9 – no valid versions exist for package DataFrames
    BayesNets v0.0.10 – no valid versions exist for package DataFrames
    BayesNets v0.1.0 – no valid versions exist for package DataFrames

 in check_metadata(::Set{String}) at /Users/ericdavies/.julia/v0.5/PkgDev/src/entry.jl:286
 in (::PkgDev.Entry.##4#9{String,Dict{String,Array{String,1}},String})(::Base.LibGit2.GitRepo) at /Users/ericdavies/.julia/v0.5/PkgDev/src/entry.jl:82
 in with(::PkgDev.Entry.##4#9{String,Dict{String,Array{String,1}},String}, ::Base.LibGit2.GitRepo) at ./libgit2/types.jl:658
 in publish(::String, ::String) at /Users/ericdavies/.julia/v0.5/PkgDev/src/entry.jl:53
 in publish() at /Users/ericdavies/.julia/v0.5/PkgDev/src/PkgDev.jl:70
```
despite the only change I've made being:
```diff
commit 9626a54d9d34e6d19aabbbff863a5a07cc7833bd
Author: Eric Davies <iamed2@gmail.com>
Date:   Thu Jul 28 11:46:03 2016 -0500

    Tag AutoHashEquals v0.0.10 [https://github.com/andrewcooke/AutoHashEquals.jl]

diff --git a/AutoHashEquals/versions/0.0.10/requires b/AutoHashEquals/versions/0.0.10/requires
new file mode 100644
index 0000000..2c4ef82
--- /dev/null
+++ b/AutoHashEquals/versions/0.0.10/requires
@@ -0,0 +1 @@
+julia 0.3
diff --git a/AutoHashEquals/versions/0.0.10/sha1 b/AutoHashEquals/versions/0.0.10/sha1
new file mode 100644
index 0000000..c232f02
--- /dev/null
+++ b/AutoHashEquals/versions/0.0.10/sha1
@@ -0,0 +1 @@
+3542065f889473ac22d0f58dc0ab57aa3c7ff32b
```

DataFrames is on `v"0.7.6"`.

**Comment by tkelman** [comment] 2016-07-28 17:42
xref https://github.com/JuliaLang/METADATA.jl/pull/5455 (which I need to fix up to now use rc's of 0.5 now that they're available), the metadata consistency check only runs on 0.4 right now so it's possible LightGraphs or similar has upper bounds that are making it infeasible on 0.5.

**Comment by tkelman** [comment] 2016-07-29 12:30
I bisected this to https://github.com/JuliaLang/METADATA.jl/pull/5675, I don't entirely understand why that caused an issue. @ararslan any guesses?

**Comment by tkelman** [comment] 2016-07-29 12:56
Okay looks like the dependency resolver is getting confused - cc @carlobaldassi, and I think this would have to be fixed in base. Setting `ENV["JULIA_PKGRESOLVE_ACCURACY"] = 2` seems to work as a temporary fix, and I'll try to put some workarounds in place in my METADATA testing PR.

**Comment by carlobaldassi** [comment] 2016-07-29 14:35
I'll investigate.

**Comment by tkelman** [comment] 2016-07-29 17:55
I merged my workaround but you should be able to reproduce by checking out older metadata. not an issue with this repo most likely

**Closed** 2016-07-29 17:54 UTC
